#Basic Git Workflow
#
# Name of the workflow
name: practice workflow

# On which action the workflow to be triggered
on: [push]

# Jobs
jobs: 
    # Job 1
    run-shell-command:
      # Using Ubuntu OS
      runs-on: ubuntu-latest
      # Array of steps to be done
      steps:
        # First step of the job
        - name: Print Hello World
          run: echo "Hello World"
    # Job 2
    run-windows-command:
      # Using Windows OS
      runs-on: windows-latest
      # To wait until any of the job to be completed before starting this job use 'needs' and pass the name of the job
      needs: ["run-shell-command"]
      # Array of steps to be done
      steps:
        - name: List all the directories
          run: dir
        - name: Print text from python
          run: print("printing a python command")
          # Type of shell to be used, It can be base, powershell and other shell type compatible with the using OS
          shell: python



