name: practice workflow

on: [push]

jobs: 
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: Print Hello World
          run: echo "Hello World"
    run-windows-comand:
      runs-on: windows-latest
      steps:
        - name: List all the directories
          run: dir
        - name: Print text from python
          run: print("printing a python command")
          shell: python